CREATE TABLE user_profiles
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    age         INTEGER,
    country     VARCHAR(255),
    preferences VARCHAR(255),
    photo_url   TEXT,
    user_id     INTEGER                                  NOT NULL,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id)
);

ALTER TABLE user_profiles
    ADD CONSTRAINT uc_user_profiles_user UNIQUE (user_id);

ALTER TABLE user_profiles
    ADD CONSTRAINT FK_USER_PROFILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

delete from user_profiles;
delete from users;

