server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://dpg-d81h8mbeo5us738cllvg-a.oregon-postgres.render.com/library_db_se3k
spring.datasource.username=library_db_se3k_user
spring.datasource.password=QSp6k5lUXl2nBpuXpAvBti6ubMSLMXQC
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
