server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://dpg-d8ukrb4vikkc738bag90-a.frankfurt-postgres.render.com:5432/bohdan_savchuk_77363
spring.datasource.username=bohdan_savchuk_77363_user
spring.datasource.password=0YHN3zeBIAP5qBMMJeSDXoNTsCYWWrfb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

google.books.api.key=AIzaSyB16wvWod1xCjJip9VS31s3vZzbEWi8d9U
google.books.api.url=https://www.googleapis.com/books/v1/volumes
google.books.default.query=bestsellers
google.books.default.maxResults=12
